/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

import Modelo.Alumno;
import Modelo.Materia;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import persistencia.AlumnoData;
import persistencia.MateriaData;

/**
 *
 * @author Usuario
 */
public class AgregarMaterias extends javax.swing.JInternalFrame {
     DefaultTableModel modelo = new DefaultTableModel();

    /**
     * Creates new form AgregarMaterias
     */
     
     Materia materia = null;
     MateriaData materiaData = new MateriaData();
     
     
    public AgregarMaterias() {
        
        
        
        
        initComponents();
        String[] columnas = {"ID", "Nombre", "Año", "Activa"};
        modelo.setColumnIdentifiers(columnas);
        tblMaterias.setModel(modelo);
        
        
        txtNombreMateria.setEnabled(false);
        txtAño.setEnabled(false);
        chkActivo.setEnabled(false);
        btnGuardar.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabelNombre = new javax.swing.JLabel();
        jLabelAnio = new javax.swing.JLabel();
        jLabelEstado = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        txtNombreMateria = new javax.swing.JTextField();
        txtAño = new javax.swing.JTextField();
        btnLimpiar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMaterias = new javax.swing.JTable();
        chkActivo = new javax.swing.JCheckBox();
        txtIdMateria = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jbIngresar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel1.setText("Gestión de Materias");

        jLabelNombre.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        jLabelNombre.setText("Nombre:");

        jLabelAnio.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        jLabelAnio.setText("Año:");

        jLabelEstado.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        jLabelEstado.setText("Estado:");

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        tblMaterias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Año", "Estado"
            }
        ));
        tblMaterias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMateriasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblMaterias);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("ID:");

        jbIngresar.setText("Ingresar");
        jbIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbIngresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(229, 229, 229)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jbIngresar)
                        .addGap(18, 18, 18)
                        .addComponent(btnGuardar)
                        .addGap(31, 31, 31)
                        .addComponent(btnActualizar)
                        .addGap(30, 30, 30)
                        .addComponent(btnEliminar)
                        .addGap(26, 26, 26)
                        .addComponent(btnBuscar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelEstado)
                            .addComponent(jLabelAnio)
                            .addComponent(jLabelNombre)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(chkActivo)
                            .addComponent(txtNombreMateria, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)
                            .addComponent(txtAño)
                            .addComponent(txtIdMateria))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 99, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnLimpiar)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel1)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkActivo, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelNombre)
                            .addComponent(txtNombreMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelAnio)
                            .addComponent(txtAño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabelEstado)))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnActualizar)
                    .addComponent(btnEliminar)
                    .addComponent(btnBuscar)
                    .addComponent(jbIngresar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLimpiar)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        
        String nombre = txtNombreMateria.getText();
        int año = Integer.parseInt(txtAño.getText());
        boolean activo = chkActivo.isSelected();
        
        materia = new Materia(nombre,año,activo);
        
        materiaData.agregarMateria(materia);
        
        
        JOptionPane.showMessageDialog(this, "Materia guardada correctamente.");
        
        txtNombreMateria.setEnabled(false);
        txtAño.setEnabled(false);
        chkActivo.setEnabled(false);
        btnGuardar.setEnabled(false);
        limpiar();
        
        txtIdMateria.setEnabled(true);
        btnActualizar.setEnabled(true);
        btnEliminar.setEnabled(true);
        btnBuscar.setEnabled(true);
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:
        int fila = tblMaterias.getSelectedRow();
        
        if (fila>=0) {
            
        
        int id =  (int) tblMaterias.getValueAt(fila, 0);
        String nombre = txtNombreMateria.getText();
        int año = (int) Integer.parseInt(txtAño.getText());
        boolean estado = (boolean) chkActivo.isSelected();
        
        materia = new Materia(id,nombre,año,estado);
        materiaData.actializarMateria(materia);
        
        
        JOptionPane.showMessageDialog(this, "Materia actualizada.");
        }else{
        JOptionPane.showMessageDialog(this, "Seleccione una fila para actualizar.");
        }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
          int fila = tblMaterias.getSelectedRow();
    if (fila >= 0) {
        modelo.removeRow(fila);
        
        int id = (int) tblMaterias.getValueAt(fila, 0);
        materiaData.eliminarMateria(id);
        
        JOptionPane.showMessageDialog(this, "Materia eliminada.");
    } else {
        JOptionPane.showMessageDialog(this, "Seleccione una fila para eliminar.");
    }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
         int idBuscado = Integer.parseInt(txtIdMateria.getText());
         
         materia = materiaData.buscarMateria(idBuscado);
        
        
        if (materia!=null) {
            cargarDatos(materia);
        }
    
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        limpiar();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void jbIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbIngresarActionPerformed
        // TODO add your handling code here:
        habilitarAgregar();
        btnActualizar.setEnabled(false);
        btnEliminar.setEnabled(false);
        btnBuscar.setEnabled(false);
        
    }//GEN-LAST:event_jbIngresarActionPerformed

    private void tblMateriasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMateriasMouseClicked
        // TODO add your handling code here:
         int fila = tblMaterias.getSelectedRow();
         
         
         
        if (fila>=0) {
             txtNombreMateria.setEnabled(true);
        txtAño.setEnabled(true);
        chkActivo.setEnabled(true);
        
         int id = (int) tblMaterias.getValueAt(fila, 0);
        String nombre = (String) tblMaterias.getValueAt(fila, 1);
        int año = (int) tblMaterias.getValueAt(fila, 2);
        boolean estado = (boolean) tblMaterias.getValueAt(fila, 3);
        
        txtIdMateria.setText(String.valueOf(id));
        txtNombreMateria.setText(nombre);
        txtAño.setText(String.valueOf(año));
        chkActivo.setSelected(estado);
        
       
        }
    }//GEN-LAST:event_tblMateriasMouseClicked

    
    public void habilitarAgregar(){
        txtIdMateria.setEnabled(false);
        btnGuardar.setEnabled(true);
        txtNombreMateria.setEnabled(true);
        txtAño.setEnabled(true);
        chkActivo.setEnabled(true);
    
    }
    
    public void cargarDatos(Materia materia){
    
        modelo.addRow(new Object[]{materia.getIdMateria(),materia.getNombre(),materia.getAnioMateria(),materia.isActivo()});
    
    }
    
    public void limpiar(){
             txtIdMateria.setText("");
    txtNombreMateria.setText("");
    txtAño.setText("");
    chkActivo.setSelected(false);
    tblMaterias.clearSelection();
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JCheckBox chkActivo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelAnio;
    private javax.swing.JLabel jLabelEstado;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbIngresar;
    private javax.swing.JTable tblMaterias;
    private javax.swing.JTextField txtAño;
    private javax.swing.JTextField txtIdMateria;
    private javax.swing.JTextField txtNombreMateria;
    // End of variables declaration//GEN-END:variables
}
